### ISSUE TITLE
`RESTfulSummarizedExperiment` usage

### ISSUE THREAD

**Issue by multimeric** [shwetagopaul92/restfulSE#17]
The `RESTfulSummarizedExperiment` class seems to have a hidden constructor, and neither the class nor its methods are documented in the manual. How then are users supposed to use it with an arbitrary HDF5 server? Is this functionality still incomplete?

**Comment by vjcitn** [comment]
Thanks for your note.  The RESTfulSummarizedExperiment class should not be used.  The repo of record for restfulSE is git@git.bioconductor.org:packages/restfulSE ... Are you trying to use this with HSDS or the tornado-based HDFS?  We wrote restfulSE mainly to work with HSDS.

**Comment by multimeric** [comment]
Sorry, do you mean that this is the wrong repo for asking questions about restfulSE? My use case is that I want to be able to host a server (using HSDS or otherwise) that will serve HDF5 data, and connect it with an R client. I thought maybe this package would be suitable. However this would depend on this package being able to connect to any arbitrary server.

**Comment by vjcitn** [comment]
Yes, this repo is not maintained any more, the developer left the Bioconductor project.  You can file issues at https://github.com/vjcitn/restfulSE/issues.  The R package is documented at 
https://bioconductor.org/packages/restfulSE ... it is a work in progress.
